<!DOCTYPE html>
<html>
<head>
    <meta charset="utf8" />
    <title>start with CSS</title>   
    <link rel="stylesheet" type="text/css" href="farHTML.css">
</head>
<body>
    <center>
    <h1>Hallo</h1>
     <div id="board"> </div>
<?php

 /*"<div id='board'>";
for ($row=1;$row<=6;$row++){
   for($colon=1;$colon<=7;$colon++){
     $cell="$row"."$colon";
     
     
    "<table>";
       echo "<tr>
                <td id='$cell'>$cell</td>.
            </tr>";
     //echo "$cell";
    }     
    echo
    "</table>";
   
    echo"<br>";
  }
 " </div>";
//for($board=0;$board<100;$board++){
 // $aryboard[$board]= $board;
//}
//foreach($aryboard as $board ){
//   echo"$board";
//}
*/

    
?>
    <script type="text/javascript" src="farHTML.js"></script>
    </center>    
</body>
    
    
</html>